PUT http://localhost:8080/events/:id
Content-Type: application/json
Authorization: <JWT TOKEN>

{
    "name": "Test event updated",
    "description": "A test event updated",
	"location": "A test location updated",
	"dateTime": "2025-03-20T15:30:00.000Z"
}
